import Head from 'next/head';

export default function Home() {
    return (
          <>
                <Head>
                        <meta charset="UTF-8" />
                        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                        <title>Patient Path | Intelligent Post-Surgical Care Communications</title>title>
                        <link rel="preconnect" href="https://fonts.googleapis.com" />
                        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                        <link
                                    href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=DM+Sans:opsz,wght@9..40,500;9..40,600&display=swap"
                                    rel="stylesheet"
                                  />
                        <style jsx>{`
                                  :root {
                                              --color-cream: #FAF8F5;
                                                          --color-sage: #7B9E87;
                                                                      --color-sage-dark: #5A7A64;
                                                                                  --color-sage-light: #EBF0EA;
                                                                                              --color-charcoal: #2D3436;
                                                                                                          --color-warm-gray: #636E72;
                                                                                                                      --color-accent: #DA4574;
                                                                                                                                  --color-white: #FFFFFF;
                                                                                                                                              --font-display: 'Instrument Serif', Georgia, serif;
                                                                                                                                                          --font-body: 'DM Sans', -apple-system, sans-serif;
                                                                                                                                                                      --shadow-soft: 0 4px 24px;
                                                                                                                                                                                }
                                                                                                                                                                                
                                                                                                                                                                                          * {
                                                                                                                                                                                                      margin: 0;
                                                                                                                                                                                                                  padding: 0;
                                                                                                                                                                                                                              box-sizing: border-box;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                  body {
                                                                                                                                                                                                                                                              background: var(--color-cream);
                                                                                                                                                                                                                                                                          color: var(--color-charcoal);
                                                                                                                                                                                                                                                                                      line-height: 1.6;
                                                                                                                                                                                                                                                                                                  overflow-x: hidden;
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                      .container {
                                                                                                                                                                                                                                                                                                                                  max-width: 1200px;
                                                                                                                                                                                                                                                                                                                                              margin: 0 auto;
                                                                                                                                                                                                                                                                                                                                                          padding: 0 24px;
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                              /* Utility Classes */
                                                                                                                                                                                                                                                                                                                                                                                        .container {
                                                                                                                                                                                                                                                                                                                                                                                                    max-width: 1200px;
                                                                                                                                                                                                                                                                                                                                                                                                                margin: 0 auto;
                                                                                                                                                                                                                                                                                                                                                                                                                            padding: 0 24px;
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                /* Navigation */
                                                                                                                                                                                                                                                                                                                                                                                                                                                          nav {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      position: fixed;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  top: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              left: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          right: 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      z-index: 1000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  background: rgba(250, 248, 245, 0.9);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              backdrop-filter: blur(20px);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          border-bottom: 1px solid rgba(123, 158, 135, 0.1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      transition: var(--transition);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        `}</style>style>
                </Head>Head>
          
                <main>
                        <section className="container">
                                  <h1 style={{ fontFamily: 'var(--font-display)' }}>Patient Path</h1>h1>
                                  <p>Intelligent Post-Surgical Care Communications</p>p>
                        </section>section>
                </main>main>
          </>>
        );
}</>
